# Generated by Django 4.2.30 on 2026-05-10 16:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/pdfs/original/')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to='downloads/pdfs/translated/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Subido / Pendiente'), ('EXTRACTING', 'Extrayendo Texto y OCR'), ('TRANSLATING', 'Traduciendo Bloques'), ('GENERATING', 'Generando Nuevo PDF'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='UPLOADED', max_length=20)),
                ('total_pages', models.IntegerField(default=0)),
                ('processed_pages', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
